AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda funksjon for å gnerer bilder

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 40
    MemorySize: 256
    LoggingConfig:
      LogFormat: JSON

    
Resources:
  GenerateImageFunction: ## Endret navnet til funksjonen
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          S3_BUCKET: "pgr301-couch-explorers" ## Lagt til S3 Bucket navn som brukes i Lambda 
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - "s3:PutObject"
            Resource:
              - "arn:aws:s3:::pgr301-couch-explorers/82/*"
        - Statement:
            Effect: Allow
            Action:
              - "bedrock:InvokeModel"
            Resource: "*"
      Events:
        GenerateImageFunction: # Endret til samme funksjon navn
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /generate-image ## Endret endepunktet
            Method: post ## Endret til post req

Outputs:
  GenerateImageApi:
    Description: API Gateway endpoint URL for Prod stage for Generate Image function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-image"

