name: Terraform Deploy

on:
  push:
    branches:
      - main
      - '**' 

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-1  
        
      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Plan (for ikke-main branches)
        if: github.ref != 'refs/heads/main'
        run: terraform plan

      - name: Terraform Apply (for main branch)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
